Update functions_ydl

diff --git a/convert/functions_ydl b/convert/functions_ydl
--- a/convert/functions_ydl
+++ b/convert/functions_ydl
@@ -25,6 +25,7 @@ prompt_for_show_details() {
   prompt "Enter the last episode number: " last_episode
 }
 
+# Function to download video for other platform
 download_video_only() {
   youtube-dl -f best "$episode_url" "$filename"
 }
@@ -97,7 +98,7 @@ download_tv_show() {
   done
 }
 
-download_other_platform() {
+download_other_tv_show() {
   show_folder="${show_name}_other"
   mkdir -p "$show_folder"
 
@@ -133,6 +134,34 @@ download_movie() {
   printf "\nDownloaded and converted subtitles for %s.\n" "$filename"
 }
 
+download_other_movie() {
+  filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
+  printf "\nDownloading %s...\n" "$filename"
+  youtube-dl -f best "$movie_url" "$filename"
+
+  printf "\nDownloaded for %s.\n" "$filename"
+}
+
+# Function to download video for the "other" platform
+download_other_platform() {
+  prompt_for_type
+
+  if [ "$type" == "tv" ]; then
+    prompt_for_show_details
+    download_other_tv_show
+  elif [ "$type" == "movie" ]; then
+    prompt "\nEnter the name of the movie (include periods between words): " movie_name
+    prompt "\nEnter the year of the movie : " movie_year
+    prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
+    prompt "Enter the movie URL: " movie_url
+
+    download_other_movie
+  else
+    printf "\nInvalid type. Please enter 'tv' or 'movie'.\n"
+    exit 1
+  fi
+}
+
 # Main function
 ydl() {
   display_menu_header
@@ -156,7 +185,6 @@ if [ "$platform" == "youtube" ]; then
       exit 1
     fi
   elif [ "$platform" == "other" ]; then
-    prompt_for_type
     download_other_platform
   else
     printf "\nInvalid platform. Please enter 'youtube' or 'other'.\n"
