Update functions_videos

diff --git a/convert/functions_videos b/convert/functions_videos
--- a/convert/functions_videos
+++ b/convert/functions_videos
@@ -101,182 +101,183 @@ m3u8() {
 
 # Function for downloading Movies & TV Shows from YouTube or other sites using Youtube-DL
 ydl() {
-	echo -e "${MENU_1_COLOR}"
-	echo " ╔═════════════════════════════════════════════════╗ "
-	echo " ║                 Movies & TV Shows               ║ "
-	echo " ║              YOUTUBE-DL to MP4 SCRIPT           ║ "
-	echo " ╚═════════════════════════════════════════════════╝ ""${RESET}"
+  echo -e "${MENU_1_COLOR}"
+  echo " ╔═════════════════════════════════════════════════╗ "
+  echo " ║                 Movies & TV Shows               ║ "
+  echo " ║              YOUTUBE-DL to MP4 SCRIPT           ║ "
+  echo " ╚═════════════════════════════════════════════════╝ ""${RESET}"
 
-	# Prompt user for platform (YouTube or other)
-	prompt "Is it YouTube or other? (Enter 'youtube' or 'other'; default: youtube): " platform "youtube"
+  # Prompt user for platform (YouTube or other)
+  prompt "Is it YouTube or other? (Enter 'youtube' or 'other'; default: youtube): " platform "youtube"
 
-	# Process based on the chosen platform
-	if [ "$platform" == "youtube" ]; then
-		# For YouTube, prompt for TV show or movie
-		prompt "\nIs it a TV show or a movie? (Enter 'tv' or 'movie'; default: tv): " type "tv"
+  # Process based on the chosen platform
+  if [ "$platform" == "youtube" ]; then
+    # For YouTube, prompt for TV show or movie
+    prompt "\nIs it a TV show or a movie? (Enter 'tv' or 'movie'; default: tv): " type "tv"
 
-		# Process based on the chosen type (tv or movie)
-		if [ "$type" == "tv" ]; then
-			# For TV shows, prompt for show details and iterate through episodes
-			prompt "\nEnter the show name (include periods between words): " show_name
+    # Process based on the chosen type (tv or movie)
+    if [ "$type" == "tv" ]; then
+      # For TV shows, prompt for show details and iterate through episodes
+      prompt "\nEnter the show name (include periods between words): " show_name
 
-			# Prompt for season and episode range
-			prompt "Enter the season number (two digits; default: 01): " season_number "01"
+      # Prompt for season and episode range
+      prompt "Enter the season number (two digits; default: 01): " season_number "01"
 
-			prompt "Enter the first episode number: " first_episode
+      prompt "Enter the first episode number: " first_episode
 
-			prompt "Enter the last episode number: " last_episode
+      prompt "Enter the last episode number: " last_episode
 
-			show_folder="${show_name}_YouTube"
-			mkdir -p "$show_folder"
+      show_folder="${show_name}_YouTube"
+      mkdir -p "$show_folder"
 
-			# Iterate through episodes, prompting for URLs and downloading
-			for ((episode = first_episode; episode <= last_episode; episode++)); do
-				episode_number=$(printf "%02d" "$episode")
+      # Iterate through episodes, prompting for URLs and downloading
+      for ((episode = first_episode; episode <= last_episode; episode++)); do
+        episode_number=$(printf "%02d" "$episode")
 
-				# Prompt for episode URL (skipping if blank)
-				printf "\nEnter the URL for Season %s Episode %s (or leave it blank to skip): " "$season_number" "$episode_number"
-				read -r episode_url
+        # Prompt for episode URL (skipping if blank)
+        printf "\nEnter the URL for Season %s Episode %s (or leave it blank to skip): " "$season_number" "$episode_number"
+        read -r episode_url
 
-				if [ -z "$episode_url" ]; then
-					printf "Skipping Season %s Episode %s.\n" "$season_number" "$episode_number"
-					continue
-				fi
+        if [ -z "$episode_url" ]; then
+          printf "Skipping Season %s Episode %s.\n" "$season_number" "$episode_number"
+          continue
+        fi
 
-				# Generate filename and download video
-				filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.1080p.WEBRip.x264.mp4"
+        # Generate filename and download video
+        filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.1080p.WEBRip.x264.mp4"
 
-				# Downloading video and converting subtitles
-				if youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$episode_url" --add-metadata -o "$filename" &&
-				    youtube-dl --write-sub --sub-lang en,en-US,en-CA,es --convert-subs vtt --skip-download -o "${filename%.*}" "$episode_url"; then
-				
-				  printf "\nConverting subtitles to SRT format...\n"
-				  vtt_files=("${filename%.*}"*.vtt)
-				
-				  for vtt_file in "${vtt_files[@]}"; do
-				    srt_file="${vtt_file%.*}.srt"
-				
-				    # Check if the VTT file exists before conversion
-				    if [ -e "$vtt_file" ]; then
-				      ffmpeg -i "$vtt_file" "$srt_file" -y
-				
-				      # Check if conversion was successful before removing the VTT file
-				      if [ $? -eq 0 ]; then
-				        rm "$vtt_file"
-				        printf "Converted %s to %s and removed the VTT file.\n" "$vtt_file" "$srt_file"
-				      else
-				        printf "${ERROR}Error converting %s to %s. Retaining the VTT file.${RESET}\n" "$vtt_file" "$srt_file"
-				      fi
-				    else
-				      printf "${ERROR}Error: VTT file %s not found for conversion.${RESET}\n" "$vtt_file"
-				    fi
-				  done
-				
-				  printf "\nDownloaded and converted subtitles for %s.\n" "$filename"
-				else
-				  echo -e "${ERROR}Error during download of ${filename}${RESET}"
-				fi
+        # Downloading video and converting subtitles
+        if youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$episode_url" --add-metadata -o "$filename" &&
+          youtube-dl --write-sub --sub-lang en,en-US,en-CA,es --convert-subs vtt --skip-download -o "${filename%.*}" "$episode_url"; then
 
-		elif [ "$type" == "movie" ]; then
-			# For movies, prompt for movie details and download
-			prompt "\nEnter the name of the movie (include periods between words): " movie_name
+          printf "\nConverting subtitles to SRT format...\n"
+          vtt_files=("${filename%.*}"*.vtt)
 
-			prompt "\nEnter the year of the movie : " movie_year
+          for vtt_file in "${vtt_files[@]}"; do
+            srt_file="${vtt_file%.*}.srt"
 
-			prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
+            # Check if the VTT file exists before conversion
+            if [ -e "$vtt_file" ]; then
+              ffmpeg -i "$vtt_file" "$srt_file" -y
 
-			prompt "Enter the movie URL: " movie_url
+              # Check if conversion was successful before removing the VTT file
+              if [ $? -eq 0 ]; then
+                rm "$vtt_file"
+                printf "Converted %s to %s and removed the VTT file.\n" "$vtt_file" "$srt_file"
+              else
+                printf "${ERROR}Error converting %s to %s. Retaining the VTT file.${RESET}\n" "$vtt_file" "$srt_file"
+              fi
+            else
+              printf "${ERROR}Error: VTT file %s not found for conversion.${RESET}\n" "$vtt_file"
+            fi
+          done
 
-			# Generate filename and download video
-			filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
-			printf "\nDownloading %s...\n" "$filename"
-			youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$movie_url" --add-metadata -o "$filename"
+          printf "\nDownloaded and converted subtitles for %s.\n" "$filename"
+        else
+          echo -e "${ERROR}Error during download of ${filename}${RESET}"
+        fi
+      done
 
-			# Download subtitles and convert to SRT format
-			printf "\nDownloading subtitles for %s.\n" "$filename"
-			youtube-dl --write-sub --sub-lang en,en-US,en-CA,es --convert-subs srt --skip-download -o "${filename%.*}" "$movie_url"
-			printf "\nDownloaded and converted subtitles for %s.\n" "$filename"
+    elif [ "$type" == "movie" ]; then
+      # For movies, prompt for movie details and download
+      prompt "\nEnter the name of the movie (include periods between words): " movie_name
 
-		else
-			# Invalid type entered
-			printf "\nInvalid type. Please enter 'tv' or 'movie'.\n"
-			exit 1
-		fi
+      prompt "\nEnter the year of the movie : " movie_year
 
-	elif [ "$platform" == "other" ]; then
-		# For other, prompt for TV show or movie
-		prompt "\nIs it a TV show or a movie? (Enter 'tv' or 'movie'): " type
+      prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
 
-		# Process based on the chosen type (tv or movie)
-		if [ "$type" == "tv" ]; then
-			# For TV shows, prompt for show details and iterate through episodes
-			prompt "\nEnter the show name (include periods between words): " show_name
+      prompt "Enter the movie URL: " movie_url
 
-			prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
+      # Generate filename and download video
+      filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
+      printf "\nDownloading %s...\n" "$filename"
+      youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$movie_url" --add-metadata -o "$filename"
 
-			prompt "Enter the season number (two digits; default: 01): " season_number "01"
+      # Download subtitles and convert to SRT format
+      printf "\nDownloading subtitles for %s.\n" "$filename"
+      youtube-dl --write-sub --sub-lang en,en-US,en-CA,es --convert-subs srt --skip-download -o "${filename%.*}" "$movie_url"
+      printf "\nDownloaded and converted subtitles for %s.\n" "$filename"
 
-			prompt "Enter the first episode number (two digits): " first_episode
+    else
+      # Invalid type entered
+      printf "\nInvalid type. Please enter 'tv' or 'movie'.\n"
+      exit 1
+    fi
 
-			prompt "Enter the last episode number (two digits): " last_episode
+  elif [ "$platform" == "other" ]; then
+    # For other, prompt for TV show or movie
+    prompt "\nIs it a TV show or a movie? (Enter 'tv' or 'movie'): " type
 
-			show_folder="${show_name}_Other"
-			mkdir -p "$show_folder"
+    # Process based on the chosen type (tv or movie)
+    if [ "$type" == "tv" ]; then
+      # For TV shows, prompt for show details and iterate through episodes
+      prompt "\nEnter the show name (include periods between words): " show_name
 
-			# Iterate through episodes, prompting for URLs and downloading
-			for ((episode = first_episode; episode <= last_episode; episode++)); do
-				episode_number=$(printf "%02d" "$episode")
+      prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
 
-				# Prompt for episode URL (skipping if blank)
-				printf "\nEnter the URL for Season %s Episode %s (or leave it blank to skip): " "$season_number" "$episode_number"
-				read -r episode_url
+      prompt "Enter the season number (two digits; default: 01): " season_number "01"
 
-				if [ -z "$episode_url" ]; then
-					printf "Skipping Season %s Episode %s.\n" "$season_number" "$episode_number"
-					continue
-				fi
+      prompt "Enter the first episode number (two digits): " first_episode
 
-				# Generate filename and download video
-				filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.${resolution}.WEBRip.x264.mp4"
-				printf "\nDownloading %s...\n" "$filename"
-				youtube-dl -f best "$episode_url" --add-metadata -o "$filename"
+      prompt "Enter the last episode number (two digits): " last_episode
 
-				printf "\nDownloaded %s.\n" "$filename"
-			done
+      show_folder="${show_name}_Other"
+      mkdir -p "$show_folder"
 
-			printf "\nAll episodes downloaded successfully.\n"
+      # Iterate through episodes, prompting for URLs and downloading
+      for ((episode = first_episode; episode <= last_episode; episode++)); do
+        episode_number=$(printf "%02d" "$episode")
 
-		elif [ "$type" == "movie" ]; then
-			# For movies, prompt for movie details and download
-			prompt "\nEnter the name of the movie (include periods between words): " movie_name
+        # Prompt for episode URL (skipping if blank)
+        printf "\nEnter the URL for Season %s Episode %s (or leave it blank to skip): " "$season_number" "$episode_number"
+        read -r episode_url
 
-			prompt "\nEnter the year of the movie: " movie_year
+        if [ -z "$episode_url" ]; then
+          printf "Skipping Season %s Episode %s.\n" "$season_number" "$episode_number"
+          continue
+        fi
 
-			prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
+        # Generate filename and download video
+        filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.${resolution}.WEBRip.x264.mp4"
+        printf "\nDownloading %s...\n" "$filename"
+        youtube-dl -f best "$episode_url" --add-metadata -o "$filename"
 
-			prompt "Enter the movie URL: " movie_url
+        printf "\nDownloaded %s.\n" "$filename"
+      done
 
-			# Generate filename and download video
-			filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
-			printf "\nDownloading %s...\n" "$filename"
-			youtube-dl -f best "$movie_url" --add-metadata -o "$filename"
+      printf "\nAll episodes downloaded successfully.\n"
 
-			printf "\nDownloaded %s.\n" "$filename"
+    elif [ "$type" == "movie" ]; then
+      # For movies, prompt for movie details and download
+      prompt "\nEnter the name of the movie (include periods between words): " movie_name
 
-		else
-			# Invalid type entered
-			printf "\nInvalid type. Please enter 'tv' or 'movie'.\n"
-			exit 1
-		fi
+      prompt "\nEnter the year of the movie: " movie_year
 
-	else
-		# Invalid platform entered
-		printf "\nInvalid platform. Please enter 'youtube' or 'other'.\n"
-		exit 1
-	fi
+      prompt "Enter the resolution (e.g., 480p, 720p, 1080p): " resolution
 
-	pause
-	show_menu_1
+      prompt "Enter the movie URL: " movie_url
+
+      # Generate filename and download video
+      filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
+      printf "\nDownloading %s...\n" "$filename"
+      youtube-dl -f best "$movie_url" --add-metadata -o "$filename"
+
+      printf "\nDownloaded %s.\n" "$filename"
+
+    else
+      # Invalid type entered
+      printf "\nInvalid type. Please enter 'tv' or 'movie'.\n"
+      exit 1
+    fi
+
+  else
+    # Invalid platform entered
+    printf "\nInvalid platform. Please enter 'youtube' or 'other'.\n"
+    exit 1
+  fi
+
+  pause
+  show_menu_1
 }
 
 # Fork function for YT-DLP instead of YOUTUBE-DL
