line indent fix

diff --git a/convert/main b/convert/main
--- a/convert/main
+++ b/convert/main
@@ -14,36 +14,36 @@
 
 # List of script URLs to download and source
 script_urls=(
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/error_handling"
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/menus"
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_videos"
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_srt"
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_cleanup"
-    "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/tmux"
-    # Add more script URLs as needed
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/error_handling"
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/menus"
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_videos"
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_srt"
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/functions_cleanup"
+  "https://raw.githubusercontent.com/jennyo88/scripts/main/convert/tmux"
+  # Add more script URLs as needed
 )
 
 # Function to source a script without download output
 source_script() {
-    local script_url=$1
-    local script_name=$(basename "${script_url}")
+  local script_url=$1
+  local script_name=$(basename "${script_url}")
 
-    # Download the script silently
-    if curl -fsSL "${script_url}" -o "${script_name}" >/dev/null 2>&1; then
-        # Source the script if download is successful
-        source "${script_name}"
-    else
-        echo "Failed to download script: ${script_url}"
-        exit 1
-    fi
+  # Download the script silently
+  if curl -fsSL "${script_url}" -o "${script_name}" >/dev/null 2>&1; then
+    # Source the script if download is successful
+    source "${script_name}"
+  else
+    echo "Failed to download script: ${script_url}"
+    exit 1
+  fi
 }
 
 # Function to remove downloaded script files
 cleanup() {
-    for url in "${script_urls[@]}"; do
-        local script_name=$(basename "${url}")
-        rm -f "${script_name}"
-    done
+  for url in "${script_urls[@]}"; do
+    local script_name=$(basename "${url}")
+    rm -f "${script_name}"
+  done
 }
 
 # Set up a trap to run the cleanup function on script exit
@@ -51,7 +51,7 @@ trap cleanup EXIT
 
 # Iterate through the list of script URLs and source each one
 for url in "${script_urls[@]}"; do
-    source_script "${url}"
+  source_script "${url}"
 done
 
 # Now you can use functions from the sourced scripts
@@ -59,8 +59,9 @@ done
 
 
 # -----------------------------------
-# MAIN MENU AND COLORS
+# MAIN MENU & COLORS
 # -----------------------------------
+main_menu="0"
 
 # Calling the load_colors() function to set color variables
 load_colors # Only loaded once
@@ -71,5 +72,5 @@ load_colors # Only loaded once
 
 while true
 do
-    show_banner_0 && show_menu_0
+  show_banner_0 && show_menu_0
 done
