Update convert

diff --git a/scripts/convert b/scripts/convert
--- a/scripts/convert
+++ b/scripts/convert
@@ -64,19 +64,6 @@ check_wget() {
     fi
 }
 
-# Function to download using either "$downloader" or yt-dlp
-downloader() {
-    local downloader
-    if command -v "$downloader" &> /dev/null; then
-        downloader="$downloader"
-    elif command -v "yt-dlp" &> /dev/null; then
-        downloader="yt-dlp"
-    else
-        echo "Error: Neither "$downloader" nor yt-dlp is installed. Please install either of them."
-        exit 1
-    fi
-}
-
 prompt() {
     local prompt="$1"
     local variable="$2"
@@ -641,10 +628,25 @@ ydl() {
 				# Generate filename and download video
 	            		filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.1080p.WEBRip.x264.mp4"
 	            		printf "\nDownloading %s...\n" "$filename"
-	            		"$downloader" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$episode_url" --add-metadata -o "$filename"
+				if command -v "youtube-dl" &> /dev/null; then
+				    youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$episode_url" --add-metadata -o "$filename"
+				elif command -v "yt-dlp" &> /dev/null; then
+				    yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$episode_url" --add-metadata -o "$filename"
+				else
+				    echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+				    exit 1
+				fi
 
 				 # Download subtitles and convert to SRT format
 	            		printf "\nDownloading subtitles for %s...\n" "$filename"
+				if command -v "youtube-dl" &> /dev/null; then
+				   youtube-dl --write-sub --sub-lang en,en-US,en-CA,es,ja --convert-subs srt --skip-download -o "${filename%.*}" "$episode_url"
+				elif command -v "yt-dlp" &> /dev/null; then
+				   yt-dlp --write-sub --sub-lang en,en-US,en-CA,es,ja --convert-subs srt --skip-download -o "${filename%.*}" "$episode_url"
+				else
+				    echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+				    exit 1
+				fi
 	            		"$downloader" --write-sub --sub-lang en,en-US,en-CA,es,ja --convert-subs srt --skip-download -o "${filename%.*}" "$episode_url"
 
 				printf "\nConverting subtitles to SRT format...\n"
@@ -676,11 +678,25 @@ ydl() {
 			# Generate filename and download video
 	        	filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
 	        	printf "\nDownloading %s...\n" "$filename"
-	        	"$downloader" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$movie_url" --add-metadata -o "$filename"
+			if command -v "youtube-dl" &> /dev/null; then
+				youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$movie_url" --add-metadata -o "$filename"
+			elif command -v "yt-dlp" &> /dev/null; then
+				yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "$movie_url" --add-metadata -o "$filename"
+			else
+				echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+				exit 1
+			fi
 
 			# Download subtitles and convert to SRT format
 			printf "\nDownloading subtitles for %s.\n" "$filename"
-			"$downloader" --write-sub --sub-lang en,en-US,en-CA,es --convert-subs srt --skip-download -o "${filename%.*}" "$movie_url"
+			if command -v "youtube-dl" &> /dev/null; then
+				youtube-dl --write-sub --sub-lang en,en-US,en-CA,es --convert-subs srt --skip-download -o "${filename%.*}" "$movie_url"
+			elif command -v "yt-dlp" &> /dev/null; then
+				yt-dlp --write-sub --sub-lang en,en-US,en-CA,es --convert-subs srt --skip-download -o "${filename%.*}" "$movie_url"
+			else
+				echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+				exit 1
+			fi
 			
 			printf "\nConverting subtitles to SRT format...\n"
 			vtt_files=("${filename%.*}"*.vtt)
@@ -739,7 +755,14 @@ ydl() {
 				# Generate filename and download video
 	            		filename="${show_folder}/${show_name}.S${season_number}E${episode_number}.${resolution}.WEBRip.x264.mp4"
 	            		printf "\nDownloading %s...\n" "$filename"
-	            		"$downloader" -f best "$episode_url" --add-metadata -o "$filename"
+				if command -v "youtube-dl" &> /dev/null; then
+					youtube-dl -f best "$episode_url" --add-metadata -o "$filename"
+				elif command -v "yt-dlp" &> /dev/null; then
+					yt-dlp -f best "$episode_url" --add-metadata -o "$filename"
+				else
+					echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+					exit 1
+				fi
 
 	            		printf "\nDownloaded %s.\n" "$filename"
 	        	done
@@ -760,7 +783,14 @@ ydl() {
 			# Generate filename and download video
 	        	filename="${movie_name}.${movie_year}.${resolution}.WEBRip.x264.mp4"
 	        	printf "\nDownloading %s...\n" "$filename"
-	        	"$downloader" -f best "$movie_url" --add-metadata -o "$filename"
+			if command -v "youtube-dl" &> /dev/null; then
+				youtube-dl -f best "$movie_url" --add-metadata -o "$filename"
+			elif command -v "yt-dlp" &> /dev/null; then
+				yt-dlp -f best "$movie_url" --add-metadata -o "$filename"
+			else
+				echo "Error: Neither youtube-dl nor yt-dlp is installed. Please install either of them."
+				exit 1
+			fi
 
 	        	printf "\nDownloaded %s.\n" "$filename"
 
